### PR TITLE
Add HDMI audio fix for Bay/Cherry Trail platform

### PR DESCRIPTION
**Pull request by piotrasd**

### CODE REVIEW

**Comment by lrusak** [comment]
Where did you get this patch?

**Comment by piotrasd** [comment]
made from github of Pierre
here

https://github.com/plbossart/sound/tree/byt-cht-hdmi-drm

and here needed changes

https://github.com/plbossart/sound/compare/c7583aec08ba04e2336bd9879a10f30d4e0cdc60...783bd2ecf918dc112cf99949303d9bc6fa5a8a75

im almost forgot, in kernel config is needed enable:
 CONFIG_SUPPORT_HDMI=y

**Comment by lrusak** [comment]
I've tried this before and it doesn't apply, there are too many changes in drm next. It needs to be rebased for 4.6

**Comment by piotrasd** [comment]
Ok i will try get update 

Wysłane z iPhone'a

Dnia 25 Apr 2016 o godz. 19:10 Lukas Rusak notifications@github.com napisał(a):

**Comment by lrusak** [comment]
Thanks, I appreciate your help

**Comment by piotrasd** [comment]
If LE 7.0 will still based od kernel 4.4 or 4.5 we can add patch there for now. Tested by me and works.
I think Pierre will make rebase for 4.6 after final version

Wysłane z iPhone'a

Dnia 25 Apr 2016 o godz. 22:34 Lukas Rusak notifications@github.com napisał(a):

**Comment by piotrasd** [comment]
@lrusak @MattDevo Hi there is updated patch for kernel 4.6 for HDMI audio on cherry Trail and bay trail 
Please if no problem apply to master
https://github.com/plbossart/sound/compare/5f271ec35cf8b637227697d31e3fe66427955433...c0a058d6abd7616ef12e7970d104ca09fc31ccbc.patch

Here source
https://github.com/plbossart/sound/commits/byt-cht-hdmi-v4.6

**Pull request closed without merging**
